apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mqtt.adapterName }}
  namespace: {{ .Values.global.namespace }}
  labels:
    component: {{ .Values.mqtt.adapterName }}
spec:
  ports:
  - port: {{ .Values.mqtt.adapterPorts.mqtt }}
    name: mqtt-mqtt
  - port: {{ .Values.mqtt.adapterPorts.ws }}
    name: mqtt-ws  
  selector:
    component: {{ .Values.mqtt.adapterName }}
  type: {{ .Values.global.serviceType}}
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.mqtt.adapterName }}
  namespace: {{ .Values.global.namespace }}
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: {{ .Values.mqtt.adapterName }}
  minReplicas: {{ .Values.global.hpa.min }}
  maxReplicas: {{ .Values.global.hpa.max }}
  metrics:
  - type: Resource
    resource:
      name: {{ .Values.global.hpa.metric }}
      targetAverageUtilization: {{ .Values.global.hpa.utilization }}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: {{ .Values.global.namespace }}
  name: {{ .Values.mqtt.adapterName }}
  labels:
    component: {{ .Values.mqtt.adapterName }}
spec:
  template:
    metadata:
      labels:
        component: {{ .Values.mqtt.adapterName }}
    spec:
      containers:
      - name: {{ .Values.mqtt.adapterName }}
        image: {{ .Values.mqttAdapterImage }}
        imagePullPolicy: {{ .Values.global.pullPolicy }}
        ports:
        - containerPort: {{ .Values.mqtt.adapterPorts.mqtt }}
          name: mqtt-mqtt
        - containerPort: {{ .Values.mqtt.adapterPorts.ws }}
          name: mqtt-ws
        env:
        {{- range $key, $value := .Values.mqtt.adapterEnv }}
            - name: {{ $key }}
              value: {{ $value | quote }}
        {{- end }}
